import Head from 'next/head'
import { ReactNode } from 'react'

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <div>
        <Head>
          <title>Home</title>
          <meta name='description' content='Generated by create-t3-app' />
          <link rel='icon' href='/favicon-32x32.png' />
        </Head>
        <header>
          <p>This is a header.</p>
        </header>
        <main>{children}</main>
        <footer>
          <p>Hello</p>
        </footer>
        <div />
      </div>
    </>
  )
}

export interface LayoutProps {
  children: ReactNode
}
