/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DisableTabsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  enabled: true,
  hideMobileNewTabIcon: false
};

// src/utils/tab-enforcer.ts
var TabEnforcer = class {
  constructor(app) {
    this.app = app;
  }
  enforceSingleTab() {
    const leaves = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      leaves.push(leaf);
    });
    if (leaves.length > 1) {
      let active = leaves[leaves.length - 1];
      for (const leaf of leaves) {
        const view = leaf.view;
        if (view && "containerEl" in view) {
          const containerEl = view.containerEl;
          if (containerEl && containerEl.hasClass("is-active")) {
            active = leaf;
            break;
          }
        }
      }
      leaves.forEach((leaf) => {
        if (leaf !== active) {
          leaf.detach();
        }
      });
    }
  }
};

// src/ui/settings-tab.ts
var import_obsidian = require("obsidian");
var DisableTabsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    // Shown beside the plugin name in settings search results (1.13) and in the
    // settings sidebar on older Obsidian (SettingTab.icon).
    this.icon = "lucide-panel-top-dashed";
    this.plugin = plugin;
    this.settings = plugin.settings;
  }
  // 1.13.0+: framework calls this and skips display().
  // Pre-1.13.0: this method is not invoked; display() below runs as before.
  // See https://docs.obsidian.md/plugins/guides/migrate-declarative-settings
  getSettingDefinitions() {
    return [
      {
        name: "Hide mobile tabs icon",
        desc: "Hide the tabs icon on mobile devices",
        // Render: changing this value has a side effect (mobile tab icon CSS update).
        render: (setting) => {
          setting.addToggle((toggle) => toggle.setValue(this.settings.hideMobileNewTabIcon).onChange(async (value) => {
            this.settings.hideMobileNewTabIcon = value;
            await this.plugin.saveSettings();
            this.plugin.updateMobileTabIconCSS();
          }));
        }
      }
    ];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const generalGroup = new import_obsidian.SettingGroup(containerEl);
    generalGroup.addSetting((setting) => {
      setting.setName("Hide mobile tabs icon").setDesc("Hide the tabs icon on mobile devices").addToggle(
        (toggle) => toggle.setValue(this.settings.hideMobileNewTabIcon).onChange(async (value) => {
          this.settings.hideMobileNewTabIcon = value;
          await this.plugin.saveSettings();
          this.plugin.updateMobileTabIconCSS();
        })
      );
    });
  }
};

// src/main.ts
var DisableTabsPlugin = class extends import_obsidian2.Plugin {
  // The main app window's document. Obsidian 1.13.0+ opens Settings in a
  // separate window, so `activeDocument` (the focused window) can point at the
  // Settings window while a setting is being changed. This feature is mobile-
  // only (where there is no separate Settings window), but using the main
  // window's document keeps it correct under desktop "emulate mobile" too.
  get doc() {
    return this.app.workspace.containerEl.ownerDocument;
  }
  async onload() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
    this.tabEnforcer = new TabEnforcer(this.app);
    this.updateMobileTabIconCSS();
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.tabEnforcer.enforceSingleTab();
    }));
    this.app.workspace.onLayoutReady(() => {
      this.tabEnforcer.enforceSingleTab();
    });
    this.addSettingTab(new DisableTabsSettingTab(this.app, this));
  }
  updateMobileTabIconCSS() {
    if (this.settings.hideMobileNewTabIcon) {
      this.doc.body.classList.add("disable-tabs-hide-mobile-icon");
    } else {
      this.doc.body.classList.remove("disable-tabs-hide-mobile-icon");
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    this.doc.body.classList.remove("disable-tabs-hide-mobile-icon");
  }
};

/* nosourcemap */